// ATTN Be sure to add the image to the images folder in the root of the project


export const logos = [
  'token/ETH',
  'token/GNO',
  'token/SSV',
  'token/xDAI',
  'token/Obol',
  'token/SWISE',
  'token/osETH',
  'token/osGNO',

  'token/ETH-dark',
  'token/GNO-dark',

  'token/WETH',
  'token/eETH',
  'token/ETHx',
  'token/mETH',
  'token/USDC',
  'token/USDT',
  'token/wBTC',
  'token/rETH',
  'token/USDS',
  'token/USDC.e',
  'token/sDAI',
  'token/EURe',
  'token/rsETH',
  'token/cbETH',
  'token/cmETH',
  'token/egETH',
  'token/ezETH',
  'token/lsETH',
  'token/stETH',
  'token/wbETH',
  'token/wxDAI',
  'token/wstETH',
  'token/frxETH',

  'connector/ledger',
  'connector/binance',
  'connector/coinbase',
  'connector/ledgerLive',
  'connector/gnosisSafe',
  'connector/walletConnect',
  'connector/monitorAddress',

  'image/file',
  'image/error',
  'image/magic',
  'image/party',
  'image/cancel',
  'image/success',
  'image/warning',
  'image/progress',
  'image/information',

  'language/en',
  'language/de',
  'language/fr',
  'language/es',
  'language/pt',
  'language/ru',
  'language/zh',

  'network/arbitrum',
] as const

export const icons = [
  'icon/dao',
  'icon/gas',
  'icon/dots',
  'icon/lock',
  'icon/user',
  'icon/plus',
  'icon/info',
  'icon/edit',
  'icon/gear',
  'icon/copy',
  'icon/link',
  'icon/home',
  'icon/lamp',
  'icon/book',
  'icon/send',
  'icon/undo',
  'icon/caret',
  'icon/share',
  'icon/token',
  'icon/trash',
  'icon/chats',
  'icon/email',
  'icon/money',
  'icon/earth',
  'icon/theme',
  'icon/close',
  'icon/check',
  'icon/users',
  'icon/minus',
  'icon/shield',
  'icon/loader',
  'icon/search',
  'icon/filter',
  'icon/upload',
  'icon/storage',
  'icon/actions',
  'icon/percent',
  'icon/control',
  'icon/support',
  'icon/rewards',
  'icon/warning',
  'icon/calendar',
  'icon/collapse',
  'icon/scrollUp',
  'icon/plusThin',
  'icon/metaVault',
  'icon/validators',
  'icon/notification',
  'icon/vaultDeposit',

  'arrow/up',
  'arrow/down',
  'arrow/left',
  'arrow/right',
  'arrowLong/up',
  'arrowLong/down',
  'arrowLong/left',
  'arrowLong/right',

  'currency/usd',
  'currency/eur',
  'currency/gbp',
  'currency/cny',
  'currency/jpy',
  'currency/krw',
  'currency/aud',

  'social/discord',
  'social/twitter',
  'social/facebook',
  'social/telegram',
  'social/discordLine',
  'social/twitterLine',
  'social/facebookLine',
  'social/telegramLine',

  'theme/sun',
  'theme/moon',
] as const


export const images = [
  ...icons,
  ...logos,
] as const

export default images
