// ATTN Be sure to add the image to the images folder in the root of the project


export const logos = [
  'token/ETH',
  'token/GNO',
  'token/SSV',
  'token/xDAI',
  'token/Obol',
  'token/SWISE',
  'token/osETH',
  'token/osGNO',

  'token/WETH',
  'token/eETH',
  'token/ETHx',
  'token/mETH',
  'token/USDC',
  'token/USDT',
  'token/wBTC',
  'token/rETH',
  'token/USDS',
  'token/USDC.e',
  'token/sDAI',
  'token/EURe',
  'token/rsETH',
  'token/cbETH',
  'token/cmETH',
  'token/egETH',
  'token/ezETH',
  'token/lsETH',
  'token/stETH',
  'token/wbETH',
  'token/wxDAI',
  'token/wstETH',
  'token/frxETH',

  'connector/MMI',
  'connector/okx',
  'connector/rabby',
  'connector/taho',
  'connector/zengo',
  'connector/ledger',
  'connector/portis',
  'connector/binance',
  'connector/coinbase',
  'connector/metamask',
  'connector/gnosisSafe',
  'connector/ledgerLive',
  'connector/trustWallet',
  'connector/braveBrowser',
  'connector/walletConnect',
  'connector/monitorAddress',

  'image/error',
  'image/magic',
  'image/success',
  'image/information',

  'language/en',
  'language/de',
  'language/fr',
  'language/es',
  'language/pt',
  'language/ru',
  'language/zh',

  'theme/sun',
  'theme/moon',
] as const

export const icons = [
  'arrow/right',
  'arrow/down',
  'arrow/left',
  'arrow/up',
  'icon/gas',
  'icon/plus',
  'icon/info',
  'icon/gear',
  'icon/copy',
  'icon/link',
  'icon/home',
  'icon/money',
  'icon/earth',
  'icon/theme',
  'icon/close',
  'icon/check',
  'icon/loader',
  'icon/search',
  'icon/upload',
  'icon/warning',
  'icon/calendar',
  'icon/scrollUp',

  'currency/usd',
  'currency/eur',
  'currency/gbp',
  'currency/cny',
  'currency/jpy',
  'currency/krw',
  'currency/aud',
] as const


export const images = [
  ...icons,
  ...logos,
] as const

export default images
