export default {
  infinityPools: {
    pools: 'ipPools',
    filters: 'ipFilters',
    deposits: 'ipDeposits',
    blacklist: 'ipBlacklist',
    categories: 'ipCategories',
  },
  swapTokenBalances: 'swapTokenBalances',
  distributorClaims: 'distributorClaims',
  vaultUnboostQueue: 'vaultUnboostQueue',
  vaultUnstakeQueue: 'vaultUnstakeQueue',
  vaultUserRewards: 'vaultUserRewards',
  allocatorActions: 'allocatorActions',
  vaultUserActions: 'vaultUserActions',
  accountBalances: 'accountBalances',
  vaultValidators: 'vaultValidators',
  depositsVaults: 'depositsVaults',
  rewardSplitter: 'rewardSplitter',
  swapTokenRates: 'swapTokenRates',
  balancerClaims: 'balancerClaims',
  osTokenVaults: 'osTokenVaults',
  operateVaults: 'operateVaults',
  vaultBalances: 'vaultBalances',
  accountWallet: 'accountWallet',
  vaultOsToken: 'vaultOsToken',
  vaultRoles: 'vaultRoles',
  vaultChart: 'vaultChart',
  fiatRates: 'fiatRates',
  mintToken: 'mintToken',
  allVaults: 'allVaults',
  vaultBase: 'vaultBase',
  encodings: 'encodings',
  currency: 'currency',
  vestings: 'vestings',
  rewards: 'rewards',
  ui: 'ui',
}
