export default {
  distributorClaims: 'distributorClaims',
  vaultUserRewards: 'vaultUserRewards',
  allocatorActions: 'allocatorActions',
  vaultUserActions: 'vaultUserActions',
  vaultUnboostQueue: 'vaultBoostQueue',
  accountBalances: 'accountBalances',
  vaultValidators: 'vaultValidators',
  depositsVaults: 'depositsVaults',
  vaultExitQueue: 'vaultExitQueue',
  rewardSplitter: 'rewardSplitter',
  osTokenVaults: 'osTokenVaults',
  operateVaults: 'operateVaults',
  vaultBalances: 'vaultBalances',
  accountWallet: 'accountWallet',
  vaultOsToken: 'vaultOsToken',
  vaultRoles: 'vaultRoles',
  vaultChart: 'vaultChart',
  fiatRates: 'fiatRates',
  mintToken: 'mintToken',
  allVaults: 'allVaults',
  vaultBase: 'vaultBase',
  encodings: 'encodings',
  currency: 'currency',
  vestings: 'vestings',
  rewards: 'rewards',
  ui: 'ui',
}
