export default {
  swapTokenBalances: 'swapTokenBalances',
  distributorClaims: 'distributorClaims',
  vaultUserRewards: 'vaultUserRewards',
  vaultUnboostQueue: 'vaultBoostQueue',
  vaultUnstakeQueue: 'vaultUnstakeQueue',
  accountBalances: 'accountBalances',
  swapTokenRates: 'swapTokenRates',
  vaultBalances: 'vaultBalances',
  vaultChart: 'vaultChart',
  fiatRates: 'fiatRates',
  mintToken: 'mintToken',
  vaultBase: 'vaultBase',
  currency: 'currency',
  vestings: 'vestings',
  rewards: 'rewards',
  ui: 'ui',
}
