/** @type {import('tailwindcss').Config} */
export default {
  content: [
    'src/**/*.{js,ts,tsx}',
  ],
  safelist: [
    { pattern: /text-[htn]\d+[bm]?/ },
    { pattern: /(bg|text|border)-(primary|button[12]-(start|end))/ },
    // TODO rename
    { pattern: /(bg|text|border)-(ocean|autumn|forest|jungle|volcano|stone|moon|sun|coal|snow|smoke)/ },
  ],
  darkMode: [ 'class', '.body-dark-theme' ],
  theme: {
    colors: {
      primary: 'rgb(var(--color-primary-rgb) / <alpha-value>)',
      'button1-start': 'rgb(var(--color-button1-start-rgb) / <alpha-value>)',
      'button1-end': 'rgb(var(--color-button1-end-rgb) / <alpha-value>)',
      'button2-start': 'rgb(var(--color-button2-start-rgb) / <alpha-value>)',
      'button2-end': 'rgb(var(--color-button2-end-rgb) / <alpha-value>)',

      autumn: 'rgb(var(--color-autumn-rgb) / <alpha-value>)',
      sunset: 'rgb(var(--color-sunset-rgb) / <alpha-value>)',
      forest: 'rgb(var(--color-forest-rgb) / <alpha-value>)',
      jungle: 'rgb(var(--color-jungle-rgb) / <alpha-value>)',
      volcano: 'rgb(var(--color-volcano-rgb) / <alpha-value>)',
      stone: 'rgb(var(--color-stone-rgb) / <alpha-value>)',
      moon: 'rgb(var(--color-moon-rgb) / <alpha-value>)',
      sun: 'rgb(var(--color-sun-rgb) / <alpha-value>)',
      coal: 'rgb(var(--color-coal-rgb) / <alpha-value>)',
      snow: 'rgb(var(--color-snow-rgb) / <alpha-value>)',
      smoke: 'rgb(var(--color-smoke-rgb) / <alpha-value>)',
      mirror: 'rgb(var(--color-mirror-rgb) / <alpha-value>)',
      titanium: 'rgb(var(--color-titanium-rgb) / <alpha-value>)',
      transparent: 'rgb(255 255 255 / 0)',
    },
    spacing: {
      'px': '1px',
      0: '0',
      4: '4rem',
      6: '6rem',
      8: '8rem',
      12: '12rem',
      16: '16rem',
      18: '18rem',
      20: '20rem',
      24: '24rem',
      32: '32rem',
      36: '36rem',
      40: '40rem',
      48: '48rem',
      56: '56rem',
      60: '60rem',
      64: '64rem',
      72: '72rem',
      80: '80rem',
      96: '96rem',
      'full': '100%',
    },
    borderWidth: {
      DEFAULT: '1px',
      '0': '0',
      '2': '2rem',
    },
    borderRadius: {
      2: '2rem',
      4: '4rem',
      6: '6rem',
      8: '8rem',
      12: '12rem',
      16: '16rem',
      24: '24rem',
      72: '72rem',
      'full': '100%',
    },
    fontSize: {
      // headers
      'h100': [ '100rem', { lineHeight: '110rem', fontWeight: '700' } ],
      'h90': [ '90rem', { lineHeight: '100rem', fontWeight: '700' } ],
      'h60': [ '60rem', { lineHeight: '72rem', fontWeight: '700' } ],
      'h48': [ '48rem', { lineHeight: '56rem', fontWeight: '700' } ],
      'h40': [ '40rem', { lineHeight: '48rem', fontWeight: '700' } ],
      'h32': [ '32rem', { lineHeight: '44rem', fontWeight: '700' } ],
      'h24': [ '24rem', { lineHeight: '32rem', fontWeight: '700' } ],
      'h22': [ '22rem', { lineHeight: '26rem', fontWeight: '700' } ],
      'h20': [ '20rem', { lineHeight: '24rem', fontWeight: '700' } ],
      // text
      't40m': [ '40rem', { lineHeight: '48rem', fontWeight: '500' } ],
      't20b': [ '20rem', { lineHeight: '32rem', fontWeight: '700' } ],
      't18m': [ '18rem', { lineHeight: '24rem', fontWeight: '500' } ],
      't18b': [ '18rem', { lineHeight: '24rem', fontWeight: '700' } ],
      't16m': [ '16rem', { lineHeight: '22rem', fontWeight: '500' } ],
      't16b': [ '16rem', { lineHeight: '22rem', fontWeight: '700' } ],
      't14': [ '14rem', { lineHeight: '20rem', fontWeight: '400' } ],
      't14m': [ '14rem', { lineHeight: '20rem', fontWeight: '500' } ],
      't14b': [ '14rem', { lineHeight: '20rem', fontWeight: '700' } ],
      't12': [ '12rem', { lineHeight: '18rem', fontWeight: '400' } ],
      't12m': [ '12rem', { lineHeight: '18rem', fontWeight: '500' } ],
      't12b': [ '12rem', { lineHeight: '18rem', fontWeight: '700' } ],
      // notes = {
      'n10': [ '10rem', { lineHeight: '16rem', fontWeight: '400' } ],
      'n10m': [ '10rem', { lineHeight: '16rem', fontWeight: '500' } ],
      'n10b': [ '10rem', { lineHeight: '16rem', fontWeight: '700' } ],
    },
    screens: {
      'mobile': { raw: '(max-width: 999px)' },
      'ex-mobile': { raw: '(min-width: 1000px)' },
      'retina': { raw: 'only screen and (-webkit-min-device-pixel-ratio: 1.5), only screen and (min-resolution: 144dpi)' },
    },
    extend: {
      opacity: {
        '02': '0.02',
        '03': '0.03',
        '04': '0.04',
        '05': '0.05',
      },
    },
  },
}
