name: E2E

on:
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    name: E2E testing
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest

    container: mcr.microsoft.com/playwright:v1.57.0-jammy

    steps:
      - name: Get preview link
        uses: zentered/vercel-preview-url@fba568fc6d882ae788a9724d7e28dee618728771
        id: preview
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_team_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJ_ID }}

      - name: Checkout 🛎️
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Setup pnpm
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1
        with:
          version: 10.25.0

      - name: Setup Node.js
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: '24.12.0'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}
        run: |
          pnpm install --frozen-lockfile --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: Awaiting WEB deployment to be ready
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}
        uses: UnlyEd/github-action-await-vercel@acd5b5d73234ad5a21031e954edaf9895643d36c
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ steps.preview.outputs.preview_url }}
          timeout: 600

      - name: Install Foundry
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}
        uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10

      - name: Run tests
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}
        env:
          CI: true
          WITH_ANVIL: true
          URL: https://${{ steps.preview.outputs.preview_url }}
          RPC_URL: ${{ secrets.RPC_URL }}
          GUARDIAN_UI_INFURA_API_KEY: ${{ secrets.GUARDIAN_UI_INFURA_API_KEY }}
          GUARDIAN_UI_ALCHEMY_API_KEY: ${{ secrets.GUARDIAN_UI_ALCHEMY_API_KEY }}
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
        run: pnpm run e2e

      - name: Upload Playwright report
        if: ${{ failure() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: vault-interface-desktop
          path: ./playwright-report/
          retention-days: 3
