name: E2E

on:
  pull_request:
    branches: [ main ]

jobs:
  audit:
    name: E2E testing
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.52.0-jammy
    steps:
      - name: Get preview link
        uses: zentered/vercel-preview-url@v1.1.9
        id: preview
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_team_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJ_ID }}

      - name: Checkout 🛎️
        uses: actions/checkout@v2
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}

      - name: Restore Node Modules
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node_modules_${{ hashFiles('package-lock.json') }}
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}

      - name: Setup node and npm
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: '24.12.0'
          cache-dependency-path: 'package-lock.json'
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}

      - name: Install npm dependencies
        run: 'npm ci --ignore-scripts || npm i --ignore-scripts --force'
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}

      - name: Awaiting WEB deployment to be ready
        uses: UnlyEd/github-action-await-vercel@v1.1.1
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ steps.preview.outputs.preview_url }}
          timeout: 600
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}

      - name: Run tests
        env:
          CI: true
          WITH_ANVIL: true
          URL: https://${{ steps.preview.outputs.preview_url }}
          RPC_URL: ${{ secrets.RPC_URL }}
          GUARDIAN_UI_INFURA_API_KEY: ${{ secrets.GUARDIAN_UI_INFURA_API_KEY }}
          GUARDIAN_UI_ALCHEMY_API_KEY: ${{ secrets.GUARDIAN_UI_ALCHEMY_API_KEY }}
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
        run: npm run e2e
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}

      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: vault-interface-desktop
          path: ./playwright-report/
          retention-days: 3
