name: E2E

on:
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    name: E2E testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Get preview link
        uses: zentered/vercel-preview-url@v1.1.9
        id: preview
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_team_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJ_ID }}

      - name: Checkout 🛎️
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}
        uses: actions/checkout@v4

      - name: Setup pnpm
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}
        uses: pnpm/action-setup@v4
        with:
          version: 10.25.0

      - name: Setup Node.js
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}
        uses: actions/setup-node@v4
        with:
          node-version: '24.12.0'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: Awaiting WEB deployment to be ready
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}
        uses: UnlyEd/github-action-await-vercel@v1.1.1
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ steps.preview.outputs.preview_url }}
          timeout: 600

      - name: Install Playwright browsers
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}
        run: pnpm exec playwright install --with-deps

      - name: Install Foundry (anvil)
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          components: anvil

      - name: Run tests
        if: ${{ steps.preview.outputs.deployment_state != 'CANCELED' }}
        env:
          CI: true
          WITH_ANVIL: true
          URL: https://${{ steps.preview.outputs.preview_url }}
          RPC_URL: ${{ secrets.RPC_URL }}
          GUARDIAN_UI_INFURA_API_KEY: ${{ secrets.GUARDIAN_UI_INFURA_API_KEY }}
          GUARDIAN_UI_ALCHEMY_API_KEY: ${{ secrets.GUARDIAN_UI_ALCHEMY_API_KEY }}
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
        run: pnpm run e2e

      - name: Upload Playwright report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: vault-interface-desktop
          path: ./playwright-report/
          retention-days: 3
